### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by SiR-PENt** [SiR-PENt/rest-country-apis#1]
Any contribution towards implementing dark mode across this site will be appreciated.

**Comment by vaishalparikh** [comment]
@SiR-PENt I would like to take this issue and try fixing it.

**Comment by SiR-PENt** [comment]
@vaishalparikh, the pleasure is all mine if you are familiar with the tech stack 🤗

**Comment by SiR-PENt** [comment]
There is a design guide folder in the repo @vaishalparikh, I believe that can be a great helper.

**Comment by Pransav290302** [comment]
@SiR-PENt  I have completed that dark mode across this site.

**Comment by SiR-PENt** [comment]
Hello @Pransav290302. 
Nice. Could you open a PR so I can review.

**Comment by Pransav290302** [comment]
i have opened a PR @SiR-PENt .

**Comment by SiR-PENt** [comment]
Seen, thank you @Pransav290302
